# Generated by Django 3.1.5 on 2021-10-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211001_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='driverscars',
            options={'verbose_name': 'Машина водителя', 'verbose_name_plural': 'Машины водителйе'},
        ),
    ]
