# Generated by Django 3.1.5 on 2021-10-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211001_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverscars',
            options={'verbose_name': 'Машина водителя', 'verbose_name_plural': 'Машины водителей'},
        ),
    ]
