# Generated by Django 3.1.5 on 2021-10-01 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211001_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='name',
            field=models.TextField(verbose_name='Имя водителя'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг (до 10)'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='surname',
            field=models.TextField(verbose_name='Фамилия водителя'),
        ),
    ]
