# Generated by Django 3.1.5 on 2021-10-01 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211001_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='description',
        ),
        migrations.AddField(
            model_name='clients',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivers',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
        ),
    ]
